### PR TITLE
Draft of Mobile Work For LA HTML Markup

### PR DESCRIPTION
**Pull request by kevklee**
Dear Alex,

My name is Kevin Lee, I am a volunteer with Hack4LA who took up front end development.

I would like to submit changes for the mobile html mark up for the project.

Thank you.

### CODE REVIEW

**Comment by alexchao** [comment]
@kevklee Thanks for contributing! I'll take a look at your branch. Do you have screenshots for how it looks in the browser? If not, no worries; I can pull your branch and click around when I have time today or this weekend.

**Comment by kevklee** [comment]
@alexchao No problem. I would like to attach a several screenshots of what it currently looks like. It is the first draft of the mobile template. Thank you~
screen shot 2017-10-06 at 1 55 32 pm
screen shot 2017-10-06 at 1 55 48 pm
screen shot 2017-10-06 at 1 55 58 pm

**Comment by kevklee** [comment]
Dear Alex,

I was able to create a responsive home page for the work for la project. 

I would like to submit another draft.

Thank you.

Sincerely,

Kevin Lee

**Comment by alexchao** [comment]
@kevklee This looks good. I can commit it for you, but first I'd like to just move all the files into the correct locations in the repo. I can do that tonight when I get home.

**Pull request closed without merging**
